language: php

install:
  - composer install --no-interaction --prefer-source

php:
  - '5.6'

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: false